### ISSUE TITLE
Throughput and memory graph issues in WebUI pipeline viewer

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#1298] opened 2024-01-22 04:51 UTC
* The throughput takes too long for the first update.
* The rounding is strange. For example, I see the graph go up and down, but the value shown is fixed at 300K.
* If you move away from the screen for too long, the throughput suddenly shoots up, showing the accumulated value from the last time the throughput update, but not dividing by the full elapsed period.

**Comment by mihaibudiu** [comment] 2024-01-31 17:00
If we are serious about incremental view maintenance we should use DBSP to generate the data for the graph.

**Comment by lalithsuresh** [comment] 2024-01-31 17:17
@mihaibudiu If you could add system tables with such data it'd make George's life easier. :)

**Comment by mihaibudiu** [comment] 2024-01-31 17:29
We'd have to work with DBSP. This is metadata generated during the pipeline execution, so there is no source the compiler can refer to or a query someone could write.

**Comment by mihaibudiu** [comment] 2024-01-31 17:37
Another issue is that the contents of these views is non-deterministic. Everything else in DBSP is a fully deterministic function of the input. But maybe this can be worked out; non-deterministic view will have very different properties for replay/fault tolerance.

**Comment by gz** [comment] 2024-01-31 18:47
duplicate of https://github.com/feldera/feldera/issues/491

**Closed** 2024-01-31 18:48 UTC
Labels: Web Console
