### ISSUE TITLE
Publish DBSP on crates.io

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#14] opened 2023-05-11 21:07 UTC
<a href="https://github.com/ryzhyk"><img src="https://avatars.githubusercontent.com/u/8323135?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryzhyk](https://github.com/ryzhyk)**
_Wed Mar 23 19:11:25 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/57_

----

### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like

-

**Comment by blp** [comment] 2023-07-26 00:13
I believe that we currently have the following barriers to releasing on crates.io:

- [X] Documentation (we've added reasonable documentation in the last few months).
- [ ] Add description, documentation, homepage, repository, readme in `Cargo.toml`.
- [ ] Add keywords and categories to `Cargo.toml` (optional).
- [ ] Issue #394.
- [ ] Issue #395.
- [ ] Get rid of big files in our tree (crates.io has a 10 MB limit), particularly `crates/dbsp/benches/galen_data.zip`.
- [ ] Another big tree is `ldbc-graphalytics-data`, which for me is showing up under `crates/dbsp` even though the tree seems to think it should be the top level. Not sure if that's a problem for me or a general problem.

**Comment by blp** [comment] 2023-07-26 17:54
Update:
- [X] Documentation (we've added reasonable documentation in the last few months).
- [ ] Add description, documentation, homepage, repository, readme in `Cargo.toml`.
- [ ] Add keywords and categories to `Cargo.toml` (optional).
- [ ] Issue #394.
- [X] Issue #395.
- [ ] Get rid of big files in our tree (crates.io has a 10 MB limit), particularly `crates/dbsp/benches/galen_data.zip`.
- [ ] Another big tree is `ldbc-graphalytics-data`, which for me is showing up under `crates/dbsp` even though the tree seems to think it should be the top level. Not sure if that's a problem for me or a general problem.

**Comment by gz** [comment] 2023-07-26 17:57
>Get rid of big files in our tree (crates.io has a 10 MB limit), particularly crates/dbsp/benches/galen_data.zip.
>Another big tree is ldbc-graphalytics-data, which for me is showing up under crates/dbsp even though the tree seems to think it should be the top level. Not sure if that's a problem for me or a general problem.

Maybe the `exclude = []` setting in Cargo.toml will help with that?

**Comment by blp** [comment] 2023-07-26 18:01
> > Get rid of big files in our tree (crates.io has a 10 MB limit), particularly crates/dbsp/benches/galen_data.zip.
> > Another big tree is ldbc-graphalytics-data, which for me is showing up under crates/dbsp even though the tree seems to think it should be the top level. Not sure if that's a problem for me or a general problem.
> 
> Maybe the `exclude = []` setting in Cargo.toml will help with that?

For `ldbc-graphalytics-data`? Yes, and `.gitignore` would work too. It's solvable, it just needs to be done.

**Comment by ryzhyk** [comment] 2023-07-26 18:03
For `galen_data.zip`, we could either download it dynamically or move the galen benchmark in a separate crate.

**Comment by blp** [comment] 2023-07-26 18:08
> For `galen_data.zip`, we could either download it dynamically or move the galen benchmark to a separate crate.

Possibly, doing anything with it would be premature optimization, because our crate is still well under the crates.io 10 MB limit:
```bash
[blp@sigxcpu dbsp]$ ls -l ../../target/package/dbsp-0.1.0.crate 
-rw-r--r--. 1 blp docker 3957315 Jul 26 10:58 ../../target/package/dbsp-0.1.0.crate
```

**Comment by ryzhyk** [comment] 2023-07-27 15:28
@blp , one more item for the todo list:

- [ ] Document the process of rolling out a coordinated release of all crates or a subset of crates using `cargo-release` or similar tool.

**Comment by blp** [comment] 2023-08-11 21:02
> @blp , one more item for the todo list:
> 
>     * [ ]  Document the process of rolling out a coordinated release of all crates or a subset of crates using `cargo-release` or similar tool.

Are we planning to publish more than just the `dbsp` crate initially?

**Comment by ryzhyk** [comment] 2023-08-11 21:15
I think we agreed to only publish `dbsp`, so we only need to document the process of publishing the dbsp crate.

**Comment by blp** [comment] 2023-08-11 21:34
> I think we agreed to only publish `dbsp`, so we only need to document the process of publishing the dbsp crate.

I haven't published a crate before. I don't have a model process to start from. Do you have any suggestion? Otherwise, I can look around a bit.

**Comment by ryzhyk** [comment] 2023-08-11 22:32
Let's use the [`cargo release`](https://crates.io/crates/cargo-release) tool.  I've had good experience with it in the past (don't remember the exact command line syntax, but I remember it being straightforward).  We can start with ad hoc manual releases and think about publishing DBSP crate from CI, in coordination with Feldera release, in the future.

**Comment by blp** [comment] 2023-08-18 22:20
I'm having trouble figuring out how to make `cargo release` work. It does the following:
1. Updates the local copy of the repository (changing the version number, for example) and commits it to a local branch.
2. Packages the code and publishes it to `crates.io`.
3. Tags the commit locally based on the version number (e.g. `v0.1.0`).
4. Pushes the tag and the local branch to the remote repository.

The problem I see is that steps 2 and 4 are not atomic, and it seems like the failure mode is bad. If you can't push the tag and the branch, then you end up with a published crate that can't be reproduced from any commit in the repository (even if the difference is just the version number):
* One reason pushing the tag and the branch would fail is that it's not possible to push directly to `main`, you need a PR. So, you can push to a different branch instead and then submit a PR. But we don't allow merges, only rebases, so what eventually gets "merged" might be different from what got built (in an arbitrary fashion because anything might have been changed in the meantime), and so you have to keep the branch around forever because that's what the tag points to (the rebased version won't have the tag on it, and rightly so).
* Suppose you can push directly to `main`. There's still a race: someone might have merged a PR between the time you start the workflow above and you did the push, so the push fails. Then, the only reasonable way to make sure that your tag and your commits get recorded for posterity is to do a merge against the updated `main` and your changes. But, again, we don't allow merges.

I see the following ways to resolve this:
1. Always release to a new branch, and then submit a PR to rebase its commit into `main`. Then the tag is on the branch instead of on `main`, which is weird but doable. The branch maybe should stay forever (because otherwise we have a tag that isn't on any branch).
2. Allow merge commits on `main`.
3. Push the tag and the commit before publishing to `crates.io`.  Then, if the push fails, you deal with it before you package and publish to `crates.io`. But `cargo release` doesn't support this workflow.

**Comment by ryzhyk** [comment] 2023-08-18 22:43
I guess the way to implement option 3 would be to run `cargo release` with `--no-publish` to prepare, tag, and push the release to github, and then publish manually using `cargo publish`... except you still have the problem with the tag being in the wrong branch.

Let's ask an expert (@Kixiron)

**Comment by ryzhyk** [comment] 2023-08-18 22:45
> The branch maybe should stay forever (because otherwise we have a tag that isn't on any branch).

A tag without a branch should work, shouldn't it?  But it does seem wrong that it will not be on the `main` branch.

**Comment by blp** [comment] 2023-08-18 23:14
> > The branch maybe should stay forever (because otherwise we have a tag that isn't on any branch).
> 
> A tag without a branch should work, shouldn't it? But it does seem wrong that it will not be on the `main` branch.

A tag without a branch does work, but it's undesirable because you can't see when you look at the `main` branch.

**Comment by blp** [comment] 2023-08-18 23:15
I suspect that `cargo-release` originated with projects where you only have one person doing pushes and merges. You don't have races in that case, so these problems don't arise.

**Comment by gz** [comment] 2023-08-19 16:37
I would propose the followng workflow:

we push a tag to github with a certain format that contains a version number. and we have a github action that runs for new tags. If it finds that the tag is a commit from main it will go off and run cargo release in CI for that tag and publish the crate.


(if a step in CI fails it could either be setup to remove the tag again or maybe some manual intervention will be necessary in this case)

**Comment by LegNeato** [comment] 2023-08-21 13:38
There is also https://crates.io/crates/cargo-smart-release FWIW. I've never used it but it was created to release the gitoxide family of crates: https://users.rust-lang.org/t/introducing-cargo-smart-release-the-new-way-to-release-workspace-crates/63561.

**Comment by gz** [comment] 2023-08-21 16:50
You can read commit message in a github action and react based on it so yes option 2 sounds good to me too!

**Comment by blp** [comment] 2023-08-23 21:06
Done, see https://crates.io/crates/dbsp

**Closed by blp** 2023-08-23 21:06 UTC
Labels: enhancement, DBSP core
