### ISSUE TITLE
Invalid rowcount on Webconsole UI home page

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1098] opened 2023-12-05 19:44 UTC
`-99.1 Krows/s`

![image](https://github.com/feldera/feldera/assets/28739668/731876d2-afc7-4809-b3ca-9e2cdb73559d)

**Comment by gz** [comment] 2023-12-05 19:59
it's a duplicate of https://github.com/feldera/feldera/issues/491 (that issue is about the graph only but it invovles the same fix (the connection should remain open when switching out of the tab or reset of connection was lost  cc @Karakatiza666)

**Closed** 2024-08-04 23:38 UTC
Labels: Web Console, User-facing
