### ISSUE TITLE
[SQL] Support User Defined Functions organized as a Rust Library

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1134] opened 2023-12-13 16:49 UTC
On the back of https://github.com/feldera/feldera/pull/1129 instead of just letting users add single Rust file with the `--udf` flag, how about we have them give a path to a rust library?
We plan on supporting a `Cargo.toml` file anyway so that they can add their own dependencies, at that point it might just be beneficial to let them plug-in a library. 

The library would be structured like a typical rust library when we do: `cargo new sqlplugin --lib`. 
```
sqlplugin
--> Cargo.toml
--> src/
------> lib.rs
------> other rust files
```

`lib.rs` would expose functions with matching signature as defined in SQL via `CREATE FUNCTION`. 

We could then add this library as a dependency, and call the functions as required.

**Comment by lalithsuresh** [comment] 2023-12-13 17:57
I suggest working through the end-to-end design first and then seeing what option works best for it:

* how would users use the pipeline-manager to submit UDFs? The REST API currently has a type called `Program` we use to represent an SQL program. Would UDFs be a part of such a `Program` object? Or are they external to it?

* Do users supply a UDF in source (single file, or a zip with a library crate), and we compile it for them (in which case, we need to think through how to integrate this with the compiler-server)? Or do the uesrs provide something like a wasm binary?

**Comment by lalithsuresh** [comment] 2023-12-13 18:17
>  Since we can supply a sql file, we should be able to supply multiple files of different types through the API.
>  It may be conceivable that in the future we'll want to also add some kind of #include mechanism to break SQL programs into multiple files, so supporting multiple SQL files would be nice too.

Multiple-programs per pipeline would be a far reaching set of changes in the pipeline-manager w.r.t to how we represent, validate, compile and run programs today.

**Comment by mihaibudiu** [comment] 2023-12-13 18:18
Not multiple programs, one program with multiple files

**Comment by lalithsuresh** [comment] 2023-12-13 18:30
Multiple files per `Program` is definitely an easier increment to start with. 

Currently, a program is a `String`. We could make it a `Vec<Source>` (name bikeshed) where `Source` is an enum that takes an SQL file or a Rust UDF. This also opens a path for writing rust programs in the future instead of SQL. :)

**Comment by ryzhyk** [comment] 2023-12-13 18:32
The simplest option seems to be to embed the UDFs inside the program.  This is what Snowflake does. 

```sql
CREATE OR REPLACE FUNCTION addone(i int)
RETURNS INT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
HANDLER = 'addone_py'
as
$$
def addone_py(i):
  return i+1
$$;
```

The spec can include dependencies, e.g., this is what Arroyo do:
```rust
/*
[dependencies]
regex = "1.10.2"
*/

use regex::Regex;

fn my_regex_matches(s: String) -> bool {
    let re = Regex::new(r"test").unwrap();
    re.is_match(&s)
}
```

Pros:
- All program code in one place
- No changes to the pipeline manager are needed

Cons:
- Hard to manage complex collections of UDFs.  The crate approach proposed by @abhizer  is much better in that respect.
- Requires more intrusive changes to the SQL compiler

**Comment by lalithsuresh** [comment] 2023-12-13 18:34
@ryzhyk Snowflake supports both modes: supplying UDF jars and inline UDFs. Inline UDFs are definitely easier for the pipeline-manager (in that all the responsibility goes to the sql compiler).

**Comment by gz** [comment] 2023-12-13 18:43
>The simplest option seems to be to embed the UDFs inside the program.

IMO even simpler would be to supply git location + revision which gets injected into the Cargo.toml of the pipeline "udf = { git = "github-url", revision = "$hash" }"

**Comment by ryzhyk** [comment] 2023-12-13 18:46
@lalithsuresh , fair enough.  So then there are two ways we can do this:

1. Start with inline UDFs. External packages can be imported as dependencies, but since there is no way for the user to upload their Rust crates, dependencies must point to `crates.io`.  Next, we add support for uploading Rust crates to the user account in some form, in which case inline UDFs can depend on those crates.

2. Stick with the current design without inline UDFs and add support for uploading Rust code to either user account or as part of a program. Introduce inline UDFs as a later extension.

**Comment by lalithsuresh** [comment] 2023-12-13 18:58
1. With inline UDFs, would the SQL compiler inline the UDF into the generated rust source? If so, it might also need to produce a`Cargo.toml` file the compiler-server can just use.

**Comment by ryzhyk** [comment] 2023-12-13 19:04
> 1. With inline UDFs, would the SQL compiler inline the UDF into the generated rust source?

yes

> If so, it might also need to produce a`Cargo.toml` file the compiler-server can just use.

yep, we can work that part out easily

**Comment by gz** [comment] 2023-12-13 19:48
inline UDFs (or any systems that mix two languages in one files) usually aren't very user-friendly, this isn't what I'd start with. 
Making a change to a udf function means you have to recompile all SQL just to find you had e.g., a syntax error in your rust, or you can't write a unit test for your function without maintaining two files and copy-pasting between the two.

**Comment by mihaibudiu** [comment] 2023-12-13 19:50
And you shouldn't expect the SQL compiler to check the piece of code between $$ signs

**Comment by lalithsuresh** [comment] 2023-12-13 21:30
So, option 2 then? @gz what kind of UI experience do you want to aim for? E.g., should users be able to edit rust in the WebConsole and get feedback, errors etc? Should there be type-checking between the SQL program and the UDFs it references?

**Comment by mihaibudiu** [comment] 2023-12-13 21:32
Can we treat the rust like a java "resource" file? Something that is just tagged along. No editing allowed, not even reading.
We can do this later for csv files too, and perhaps config files if needed.

**Comment by ryzhyk** [comment] 2023-12-13 21:43
> Can we treat the rust like a java "resource" file? Something that is just tagged along. No editing allowed, not even reading. We can do this later for csv files too, and perhaps config files if needed.

Yeah, I don't think we want to ship a Rust IDE with the product :)

**Comment by ryzhyk** [comment] 2023-12-13 21:53
Follow-up questions:
- We need to introduce the notion of a resource associated with either a program or a user account. What is the API/UI for that? 
- What exactly is the artifact we want to upload?  Single crate?  Multiple crates?  Rust workspace?
- Reporting compilation errors in the user Rust code.

**Comment by mihaibudiu** [comment] 2023-12-13 21:55
The problem with Rust compilation errors is not necessarily new, it can arise due to bugs in the SQL compiler too.
A crate should be enough for now.

**Comment by ryzhyk** [comment] 2023-12-13 22:01
> We need to introduce the notion of a resource associated with either a program or a user account. What is the API/UI for that?

@lalithsuresh , do you want to suggest an API extension.  We can the design the UI around that?

> What exactly is the artifact we want to upload? Single crate? Multiple crates? Rust workspace?

Multiple crates seems nicer, as this way users can build reusable libraries of these functions, and I don't think this will complicate any aspect of the design significantly.  One question is whether we want to scope UDF function names to crates or use a flat namespace.
 
> Reporting compilation errors in the user Rust code.

There are two new types of Rust errors
- A compilation error in a UDF crate.
- A compilation error in the main crate caused by a function signature mismatch.

As @mihaibudiu  suggested, we can treat both as any other Rust error caused by invalid generated code , but at least for the first type of error we should be able to do better.

**Comment by lalithsuresh** [comment] 2023-12-13 22:27
> We need to introduce the notion of a resource associated with either a program or a user account. What is the API/UI for that?

How about this https://github.com/feldera/feldera/issues/1134#issuecomment-1854501342?

Idea is to make a `Program` a list of `Sources`. A `Source` can be an SQL file or a Rust UDF (assuming single file, but maybe a crate too).

**Comment by gz** [comment] 2023-12-13 22:29
> Follow-up questions:
> 
>     1. We need to introduce the notion of a resource associated with either a program or a user account. What is the API/UI for that?
> 
>     2. What exactly is the artifact we want to upload?  Single crate?  Multiple crates?  Rust workspace?

I'd solve both of these by having the SQL compiler inject a dependency through Cargo.toml. You don't need to support uploading anything -- just reference a git URL + revision as part of SQL. 
Also can keep APIs unchanged (aside from adding a new error type).

**Comment by mihaibudiu** [comment] 2023-12-13 22:30
List may not be enough, the relative placement in directories may matter.
For example, we may want a cargo.toml file
I find the idea of needing to push something to git just to test if it works onerous.

**Comment by ryzhyk** [comment] 2023-12-13 22:38
> I find the idea of needing to push something to git just to test if it works onerous.

I agree, this seems too extreme.  In addition to being hard to use, this is also frighteningly insecure.

**Comment by lalithsuresh** [comment] 2023-12-13 22:40
Using `git` also has the issue that we'd need to support credentials and secret management to specify programs, not to mention network connectivity problems.

**Comment by lalithsuresh** [comment] 2023-12-13 22:51
> List may not be enough, the relative placement in directories may matter. For example, we may want a cargo.toml file

SQL files can be one file per entry in the list. A rust UDF might be a single entry representing a whole crate. 

Alternatively, an even simpler API would be:
```
Program {
    sql: String, // one SQL file
    udfs: Option<Udf>
}
```

Where `Udf` could be whatever format you folks agree on (e.g., zipfile of the whole crate). We store `Udf` as a blob in the DB.

I assume the plan here is for the UI to display the UDF but not allow editing, right?

**Comment by gz** [comment] 2023-12-14 00:33
> this is also frighteningly insecure.

I don't think this is more/less secure vs. the user providing the code through an API.

> I assume the plan here then is for the UI to display the UDF but not allow editing, right?

I think if we want to supply it through an API we should make sure we can edit it in the UI. We can make the editor have multiple tabs that shouldn't be too hard.

**Comment by ryzhyk** [comment] 2023-12-14 01:02
> I think if we want to supply it through an API we should make sure we can edit it in the UI. We can make the editor be able to edit multiple files (e.g., with tabs) that shouldn't be too hard.

UI editing can consist of uploading files that contain Rust crates.

**Comment by ryzhyk** [comment] 2024-08-27 22:21
Closing in favor of https://github.com/feldera/feldera/issues/2353

**Closed by ryzhyk** 2024-08-27 22:21 UTC
Labels: SQL compiler
