### ISSUE TITLE
Feldera GUI bug: ad-hoc queries always show one row less

### ISSUE THREAD

**Issue by rodonile** [feldera/feldera#3117] opened 2024-12-09 14:19 UTC
**Describe the bug**
The ad-hoc queries always show one row less than the existing rows in the view.

**To Reproduce**
- Ingest couple of messages like (SQL code below):

```
curl -i -X 'POST' 'http://localhost:8080/v0/pipelines/vmware/ingress/sonata?format=json' -d '{"insert":{"hostname": "VMWare-ESXI3-vSwitches", "loopbackAddress": "::ffff:138.187.58.104", "platform": {"name": "VMWare"}}}'
curl -i -X 'POST' 'http://localhost:8080/v0/pipelines/vmware/ingress/sonata?format=json' -d '{"insert":{"hostname": "DAISY-90", "loopbackAddress": "2001:db8:90::1", "platform": {"name": "IETF-LAB"}}}'
curl -i -X 'POST' 'http://localhost:8080/v0/pipelines/vmware/ingress/sonata?format=json' -d '{"insert":{"hostname": "DAISY-91-IPv4", "loopbackAddress": "::ffff:203.0.113.91", "platform": {"name": "IETF-LAB"}}}'
curl -i -X 'POST' 'http://localhost:8080/v0/pipelines/vmware/ingress/sonata?format=json' -d '{"insert":{"hostname": "DAISY-91", "loopbackAddress": "2001:db8:91::1", "platform": {"name": "IETF-LAB"}}}'
```

**Expected behavior**
I would expect the ad-hoc query displaying the 4 rows. As we can see from the stream output, all 4 messages are correctly ingested. The ad-hoc query even recognizes there are 4 rows, however it only displays 3, see screenshot below.

**Screenshots**
![snapshot](https://github.com/user-attachments/assets/c5c8ad0e-e319-411d-bc65-4e45b62a7137)

**Context (please complete the following information):**
 - Feldera Version: v0.31.2, commit https://github.com/feldera/feldera/commit/5563b410ed25039d47ea0dee42905b3e035a4d50
 - Environment: Native
 - Browser: Firefox
 - Pipeline Configuration/SQL code:

```
-- Input Table for platform ID and node ID enrichment
CREATE TABLE sonata (
  hostname VARCHAR NOT NULL,
  loopbackAddress VARCHAR NOT NULL,
  platform MAP<VARCHAR, VARCHAR> NOT NULL
);

-- Simplified node_id / platform_id table to be used for JOINs
CREATE MATERIALIZED VIEW sonata_enrichment AS
  SELECT
    loopbackAddress,
    hostname as node_id,
    platform['name'] as platform_id
  FROM sonata;

```

**Comment by ryzhyk** [comment] 2024-12-09 16:03
@rodonile , is there any chance there's a scrollbar hiding near the ad hoc query output? Just tried this on firefox and wasn't able to reproduce yet.

**Comment by ryzhyk** [comment] 2024-12-09 16:05
Also, could you please confirm that `fda` returns correct result for the query:

```
fda --host http://localhost:8080 query vmware 'select * from sonata_enrichment'
```

**Comment by rodonile** [comment] 2024-12-10 08:03
> Also, could you please confirm that `fda` returns correct result for the query:
> 
> ```
> fda --host http://localhost:8080 query vmware 'select * from sonata_enrichment'
> ```

Yes this gives the correct result, also testing on chrome browser I get the expected 4 lines.



> @rodonile , is there any chance there's a scrollbar hiding near the ad hoc query output? Just tried this on firefox and wasn't able to reproduce yet.

I don't see a scrollbar, that's strange then. Might be an issue with my specific firefox setup only then if on your side is working.

**Comment by rodonile** [comment] 2024-12-10 08:18
In this new test with 6 rows, I now can see the scrollbar, but still even if I scroll it I only see 5 rows

![ex2](https://github.com/user-attachments/assets/d8f2d5b3-4948-484e-a490-8fa9d1045516)

**Comment by Karakatiza666** [comment] 2024-12-10 16:54
@rodonile I assume you have the latest Firefox version. What OS are you using?

**Comment by Karakatiza666** [comment] 2024-12-10 17:20
I would also kindly ask to open a Dev panel inside your browser (F12), click on the "Console" tag, and copy-paste/screenshot the contents if there are any errors there.
Your Change Stream table looks off, too, and I am having trouble reproducing any of this in Ubuntu 24.

**Comment by Karakatiza666** [comment] 2024-12-12 15:00
Cannot reproduce with the same commit in an updated Firefox v. 133.0.3 on Windows 11 Home update 23H2.
I tried to produce a screenshot comparable to your first one:
<img width="1888" alt="image" src="https://github.com/user-attachments/assets/ecf335e0-b040-4cb5-9fbd-9abb15dff67b" />
I get the same CSS warnings as you in the in-browser console, so they should not be related to the issue.

As you can see, in your screenshot there are some other instances of incorrect rendering compared to my screenshot:

- Of the "Pipeline Resources Configuration" button
- Of the AdHoc query Start and Delete buttons
- Of the padding space above the green "SQL" checkmark icon

The only hypothesis I have is there could be some system-wide, or in-browser text scaling applied that affects some styles?
I will try to come up with any other possible causes to reproduce.

**Comment by Karakatiza666** [comment] 2024-12-12 15:05
Also, would be great if you could confirm if the issue is the same for you after you

- start the pipeline
- Open and click anywhere **inside** the Change Stream tab
- Ctrl + V the following JSON:

```
[
  {"insert":{"hostname": "VMWare-ESXI3-vSwitches", "loopbackAddress": "::ffff:138.187.58.104", "platform": {"name": "VMWare"}}, "relationName": "sonata"},
  {"insert":{"hostname": "DAISY-90", "loopbackAddress": "2001:db8:90::1", "platform": {"name": "IETF-LAB"}}, "relationName": "sonata"},
  {"insert":{"hostname": "DAISY-91-IPv4", "loopbackAddress": "::ffff:203.0.113.91", "platform": {"name": "IETF-LAB"}}, "relationName": "sonata"},
  {"insert":{"hostname": "DAISY-91", "loopbackAddress": "2001:db8:91::1", "platform": {"name": "IETF-LAB"}}, "relationName": "sonata"}
]
```
- Run "select * from sonata_enrichment" ad-hoc query

**Comment by rodonile** [comment] 2024-12-13 08:53
I tested on firefox in my personal linux notebook, and there I also do not see the issue. I agree with you, might be some particular system configuration or customization only unique to my work laptop. As far as I'm concerned this issue can be closed.
Thanks a lot for investigating!

**Comment by ryzhyk** [comment] 2024-12-13 16:27
Reopening, since it clearly hasn't been resolved

**Comment by Karakatiza666** [comment] 2024-12-19 10:31
I was able to reproduce this in Firefox on Ubuntu - for me the issue reproduced when there were more than 10 rows in a query result.
The fix for this issue doesn't account for other minor discrepancies in the UI that can be seen on attached screenshots

**Closed** 2024-12-19 20:23 UTC
Labels: bug, Web Console
