### ISSUE TITLE
Graph in the UI depends on whether the tab is in focus

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#911] opened 2023-10-19 21:51 UTC
We were running a steady workload of 5 reqs/sec, which was visible in the graph in the pipeline viewer. If I change focus to another tab for a while and come back to it, I see a sudden spike (e.g., I just saw 2k reqs/sec), before it goes back to 5 reqs/sec.

It seems like the counter accumulates behind-the-scenes but time isn't being advanced, which gives the misleading throughput measurement.

**Comment by ryzhyk** [comment] 2023-10-19 21:57
This is a duplicate of #491. The solution involves using a proper metrics server like prometheus.

**Comment by lalithsuresh** [comment] 2023-10-19 22:02
Okay, closing since it's a duplicate.

**Closed** 2023-10-19 22:02 UTC
Labels: Web Console
