### ISSUE TITLE
Trying to start a previously failed pipeline does not work with the pipeline API

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1819] opened 2024-06-01 03:32 UTC
Trying to start a previously failed pipeline does not work with the pipeline API:

(it needs to explicitly clear the error of the failed pipeline)

```
Running the training pipeline. Point your browser to http://localhost:8080/streaming/management/ to monitor the status of the pipeline.
Traceback (most recent call last):
  File "/home/gz/workspace/dbsp/python/feldera/rest/_httprequests.py", line 147, in __validate
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8080/v0/pipelines/fraud_detection_training/pause

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gz/workspace/dbsp/demo/project_demo10-FraudDetectionDeltaLake/run.py", line 346, in <module>
    main()
  File "/home/gz/workspace/dbsp/demo/project_demo10-FraudDetectionDeltaLake/run.py", line 125, in main
    sql.run_to_completion()
  File "/home/gz/workspace/dbsp/python/feldera/sql_context.py", line 390, in run_to_completion
    self.pause()
  File "/home/gz/workspace/dbsp/python/feldera/sql_context.py", line 445, in pause
    self.client.pause_pipeline(self.pipeline_name)
  File "/home/gz/workspace/dbsp/python/feldera/rest/client.py", line 334, in pause_pipeline
    self.http.post(
  File "/home/gz/workspace/dbsp/python/feldera/rest/_httprequests.py", line 106, in post
    return self.send_request(requests.post, path, body, content_type, params, stream=stream)
  File "/home/gz/workspace/dbsp/python/feldera/rest/_httprequests.py", line 80, in send_request
    resp = self.__validate(request)
  File "/home/gz/workspace/dbsp/python/feldera/rest/_httprequests.py", line 151, in __validate
    raise FelderaAPIError(str(err), request) from err
feldera.rest.errors.FelderaAPIError: FelderaAPIError: 400 Client Error: Bad Request for url: http://localhost:8080/v0/pipelines/fraud_detection_training/pause
 Error code: IllegalPipelineStateTransition
 Error message: Action is not applicable in the current state of the pipeline: Cannot restart a failed pipeline. Clear the error state first by invoking the '/shutdown' endpoint.
 Details: {'current_status': 'Failed', 'desired_status': 'Running', 'error': "Cannot restart a failed pipeline. Clear the error state first by invoking the '/shutdown' endpoint.", 'pipeline_id': '018fcfe4-d106-7f4d-b58a-2f4a350b1e61', 'requested_status': 'Paused'}
```

**Comment by ryzhyk** [comment] 2024-06-01 15:32
This behavior is intentional. We may want to change it, but today this is by design. It is meant to prevent the situation when the user calls `pause`/`resume` on the pipeline not realizing that the pipeline has failed and they are actually creating a new pipeline rathen than pausing/resuming an existing one.

**Comment by gz** [comment] 2024-06-01 20:19
Ok maybe thenwe should at least have a better error message that instructs the user on how to resolve this.

**Comment by ryzhyk** [comment] 2024-06-01 20:25
Agreed. #1797 is related.

**Comment by abhizer** [comment] 2024-10-02 14:26
Closing as it is no longer applicable for the newer API. 

- `PipelineBuilder.create_or_replace()` replaces and restarts any failed pipeline. 
- `PipelineBuilder.create()` fails because the pipeline already exists, regardless of what state it is in. 
- `Pipeline.get()` gets the pipeline, but subsequent call to `start()` fails as intended as the pipeline is in failed state. 
  - Call `restart()` instead (or manually shutdown the pipeline before re-starting).

**Closed by abhizer** 2024-10-02 14:26 UTC
Labels: python-sdk
