### ISSUE TITLE
SQL compile errors not show in SQL Program Editor

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1245] opened 2024-01-10 19:37 UTC
SQL
```
CREATE TABLE event_t (
id BIGINT NOT NULL PRIMARY KEY,
site_id BIGINT NOT NULL FOREIGN KEY REFERENCES site_t (id),
eqid STRING,
serial_num STRING,
event_type_id BIGINT NOT NULL FOREIGN KEY REFERENCES eventtype_t (id),
event_date BIGINT NOT NULL, -- epoch
event_date_timestamp TIMESTAMP,
emu_event_id INT,
message_key INT,
message_params STRING, -- json map type
alarm_id BIGINT,
event_clear_date BIGINT, -- epoch
event_clear_date_timestamp TIMESTAMP,
updated_at TIMESTAMP,
standing INT,
local_event_dts TIMESTAMP,
local_event_dt DATE
);

CREATE TABLE eventtype_t (
    id BIGINT NOT NULL PRIMARY KEY,
    name STRING NOT NULL
);

CREATE TABLE site_t (
    id BIGINT NOT NULL PRIMARY KEY,
    name STRING NOT NULL
);

CREATE VIEW TOP_EVENT_DURATIONS_V AS
SELECT duration
,      site_id
,      ROW_NUMBER() OVER (PARTITION BY site_id
                          ORDER BY duration ASC) AS rnum
FROM   EVENT_DURATION_V
WHERE  rnum = 1
;
```

Error in UI.
![image](https://github.com/feldera/feldera/assets/28739668/fe9caeae-030f-4e3e-bce5-f209a4bafb29)

**Comment by mihaibudiu** [comment] 2024-01-10 20:45
This is a duplicate of https://github.com/feldera/feldera/issues/364
It is also related to #1040 
I will close this version.

**Closed** 2024-01-10 20:46 UTC
Labels: duplicate, Web Console, UX
