### ISSUE TITLE
OVER currently does not support sorting on nullable column

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1175] opened 2023-12-21 06:30 UTC
1. SQL
```
CREATE TABLE event_t (
id BIGINT NOT NULL PRIMARY KEY,
site_id BIGINT NOT NULL,
event_type_id BIGINT NOT NULL,
event_date BIGINT NOT NULL, -- epoch
event_clear_date BIGINT -- epoch
);

CREATE VIEW EVENT_DURATION_V AS
SELECT (event_date - event_clear_date) AS duration
,      event_type_id
,      site_id
FROM   event_t
WHERE  event_clear_date IS NOT NULL
;

CREATE VIEW TOP_EVENT_DURATIONS_V AS
SELECT (duration * -1) as duration
,      event_type_id
FROM   (SELECT duration
        ,      event_type_id
        ,      ROW_NUMBER() OVER (PARTITION BY event_type_id
                                  ORDER BY duration ASC) AS rnum
        FROM   EVENT_DURATION_V)
WHERE   rnum <= 3
;
```
2. Error
```
Program status: {'SqlError': [{'startLineNumber': 0, 'startColumn': 0, 'endLineNumber': 0, 'endColumn': 0, 'warning': False, 'errorType': 'Not yet implemented', 'message': "OVER currently does not support sorting on nullable column 'DURATION': SELECT `DURATION`, `EVENT_TYPE_ID`, `SITE_ID`, ROW_NUMBER() OVER (PARTITION BY `EVENT_TYPE_ID` ORDER BY `DURATION`) AS `w0$o0`\nFROM `schema`.`EVENT_DURATION_V`"}]}
```

**Comment by mihaibudiu** [comment] 2023-12-21 07:36
This issue is a duplicate of #457 as stated.
However, this code should be recognized as a TopK instead of as an OVER query.
A fix is upcoming and handles both this example and the one in #1174.
In the meantime I will close this issue.

**Closed by mihaibudiu** 2023-12-21 07:36 UTC
Labels: bug, SQL compiler, User-facing
