### ISSUE TITLE
[UI] broken icons when searching the editor using ctrl+f

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2597] opened 2024-09-27 21:18 UTC
Reported by @xiasongh

![image](https://github.com/user-attachments/assets/a83f7867-7a8d-4b7d-949f-8cde4921c326)

**Comment by gz** [comment] 2024-09-27 23:56
it's a duplicate of https://github.com/feldera/feldera/issues/2579

**Closed** 2024-10-01 05:57 UTC
Labels: Web Console, high priority
