### ISSUE TITLE
[JIT] Jit compiler panic

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#66] opened 2023-05-12 07:36 UTC
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Fri Apr 14 22:51:03 2023_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/372_

----

Yet another kind of panic:
```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `String`,
 right: `String`', crates/dataflow-jit/src/ir/validate.rs:970:17
```
JSON:
```
{
  "nodes" : {
    "11797" : {
      "Source" : {
        "layout" : 1,
        "table" : "T"
      }
    },
    "11841" : {
      "Map" : {
        "input" : 11797,
        "map_fn" : {
          "args" : [ {
            "id" : 1,
            "layout" : 1,
            "flags" : "input"
          }, {
            "id" : 2,
            "layout" : 2,
            "flags" : "output"
          } ],
          "ret" : "Unit",
          "entry_block" : 1,
          "blocks" : {
            "1" : {
              "id" : 1,
              "body" : [ [ 3, {
                "Load" : {
                  "source" : 1,
                  "source_layout" : 3,
                  "column" : 3,
                  "column_type" : "String"
                }
              } ], [ 4, {
                "Constant" : {
                  "String" : " "
                }
              } ], [ 5, {
                "Constant" : {
                  "Bool" : false
                }
              } ], [ 6, {
                "BinOp" : {
                  "lhs" : 3,
                  "rhs" : 4,
                  "kind" : "Or",
                  "operand_ty" : "String"
                }
              } ], [ 7, {
                "Load" : {
                  "source" : 1,
                  "source_layout" : 3,
                  "column" : 3,
                  "column_type" : "String"
                }
              } ], [ 8, {
                "Constant" : {
                  "Bool" : false
                }
              } ], [ 9, {
                "BinOp" : {
                  "lhs" : 6,
                  "rhs" : 7,
                  "kind" : "Or",
                  "operand_ty" : "String"
                }
              } ], [ 10, {
                "Store" : {
                  "target" : 2,
                  "target_layout" : 2,
                  "column" : 0,
                  "value" : {
                    "Expr" : 9
                  },
                  "value_type" : "String"
                }
              } ] ],
              "terminator" : {
                "Return" : {
                  "value" : {
                    "Imm" : "Unit"
                  }
                }
              }
            }
          }
        },
        "layout" : 2
      }
    },
    "11843" : {
      "Sink" : {
        "input" : 11841,
        "query" : "CREATE VIEW V AS SELECT T.COL4 || ' ' || T.COL4 FROM T"
      }
    }
  },
  "layouts" : {
    "1" : {
      "columns" : [ {
        "nullable" : false,
        "ty" : "I32"
      }, {
        "nullable" : false,
        "ty" : "F64"
      }, {
        "nullable" : false,
        "ty" : "Bool"
      }, {
        "nullable" : false,
        "ty" : "String"
      }, {
        "nullable" : true,
        "ty" : "I32"
      }, {
        "nullable" : true,
        "ty" : "F64"
      } ]
    },
    "2" : {
      "columns" : [ {
        "nullable" : false,
        "ty" : "String"
      } ]
    },
    "3" : {
      "columns" : [ {
        "nullable" : false,
        "ty" : "I32"
      }, {
        "nullable" : false,
        "ty" : "F64"
      }, {
        "nullable" : false,
        "ty" : "Bool"
      }, {
        "nullable" : false,
        "ty" : "String"
      }, {
        "nullable" : true,
        "ty" : "I32"
      }, {
        "nullable" : true,
        "ty" : "F64"
      } ]
    }
  }
}
```

**Comment by mihaibudiu** [comment] 2023-10-04 21:33
the format has changed too much in the meantime, so I will close this issue because it can't be reproduced

**Closed by mihaibudiu** 2023-10-04 21:33 UTC
Labels: bug, JIT
